# Screen settings
OFFSET = 75
CELL_SIZE = 40
CELL_NUMBER = 25
WIDTH = CELL_SIZE * CELL_NUMBER + 2 * OFFSET
HEIGHT = CELL_SIZE * CELL_NUMBER + 2 * OFFSET

# Colors
GRASS = (1, 46, 11)
WHITE = (255, 255, 255)

# Game Save
SAVE_PATH = "./" + "save.json"